services:
  pgdb:
    container_name: "pgdb"
    image: "postgres:latest"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
    ports:
      - "5432:5432"
    networks:
      - base-network
  pgadmin:
    container_name: "pgadmin"
    image: "dpage/pgadmin4"
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    networks:
      - base-network
  rdb:
    container_name: "rdb"
    image: "redis:latest"
    ports:
      - "6379:6379"
    networks:
      - base-network
  rdb-insight:
    image: redis/redisinsight:latest
    restart: always
    ports:
      - "5540:5540"
    networks:
      - base-network

networks:
  base-network:
    external: true