services:
  todo-app:
    container_name: 'todo-app'
    image: 'todo-app'
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '8082:8082'
    networks:
      - base-network

networks:
  base-network:
    external: true
