services:
  todo-app:
    container_name: 'todo-app'
    image: 'todo-app'
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - POSTGRES_URI=${POSTGRES_URI}
      - PORT=${PORT}
      - BROKER_HOST=${BROKER_HOST}
      - BROKER_PORT=${BROKER_PORT}
      - REDIS_URI=${REDIS_URI}
      - SECRET_KEY=${SECRET_KEY}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_SECURE=${EMAIL_SECURE}
      - EMAIL_SERVICE=${EMAIL_SERVICE}
      - TIME_NOTIFY_REMINDER=${TIME_NOTIFY_REMINDER}
    ports:
      - '8082:8082'
    networks:
      - base-network

networks:
  base-network:
    external: true
