name: Deploy to Staging

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/todo-app:${{ github.sha }}
            ${{ secrets.DOCKER_USERNAME }}/todo-app:${{ github.event.inputs.environment }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/todo-app:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/todo-app:buildcache,mode=max
      
      - name: Deploy notification
        run: |
          echo "Deployed to ${{ github.event.inputs.environment }}"
          echo "Image: ${{ secrets.DOCKER_USERNAME }}/todo-app:${{ github.sha }}"